### ISSUE TITLE
need dynamic modification log level

### ISSUE THREAD

**Issue by xiaoyan648** [go-leo/leo#1]
i want use ` func (l *Logger) ServeHTTP(resp http.ResponseWriter, req *http.Request)` to dynamic modification log level.
but The current code is as follows：
<img width="674" alt="image" src="https://user-images.githubusercontent.com/49704763/188282252-06d5d26c-d1d0-46d1-aa9a-4a40c24e3872.png">

When ` level.Level()` level will be copy, No longer be controlled by `(L *Logger) server`.  
Can you change the method of `newConsOleCore` to the following：
<img width="717" alt="image" src="https://user-images.githubusercontent.com/49704763/188282338-5b9d5008-95eb-4c4a-b77e-49eb1401919a.png">

**Comment by soyacen** [comment]
fixed
